if (GetLocale() ~= "enGB" and GetLocale() ~= "enUS"
-- other localizations fix
and GetLocale() ~= "deDE"
and GetLocale() ~= "esES"
and GetLocale() ~= "esMX"
and GetLocale() ~= "frFR"
and GetLocale() ~= "koKR"
and GetLocale() ~= "zhCN"
and GetLocale() ~= "zhTW"
) then return end

MHExRTL.panelbossmodsradenonly25 = "Only for 25ppl"
MHExRTL.panelbossmodsalpha = "Alpha"
MHExRTL.panelbossmodsscale = "Scale"
MHExRTL.panelbossmodsclose = "Close"
MHExRTL.panelbossmodsmalkorok ="Malkorok"
MHExRTL.panelbossmodsmalkorokh = "Malkorok Helper"
MHExRTL.panelbossmodsmalkorokai ="Malkorok AI"
MHExRTL.panelbossmodsmalkorokhelp ="Malkorok bossmod. Left click to choice, right click to cancel."
MHExRTL.panelbossmodsmalkorokaihelp ="Malkorok AI bossmod. Automatic selection with the least amount of people during the AOE. Highlighted in orange for 5 seconds.  Enough to be launched at the same time only one person in the raid with assist."
MHExRTL.panelbossmodsmalkorokdanger ="! Danger !"
MHExRTL.panelsetauthor = "Author"